"""
Google Forms Configuration for PBP Client Order Forms

This module contains all configuration for the Google Forms integration:
- Form and response sheet URLs
- Entry ID mappings for pre-filled URLs
- Field names and validation rules

Created: 2026-01-20
Form: PBP Client Order Form - Master
"""

# ============================================================
# GOOGLE FORM URLS
# ============================================================

GOOGLE_FORM_CONFIG = {
    # Public form URL (what clients see)
    'form_url': 'https://docs.google.com/forms/d/e/1FAIpQLSeqkiNJbalPNWPa2DjizAEbOPGlTxbkgE76Bldqk08yFymCjA/viewform',

    # Response Google Sheet URL
    'response_sheet_url': 'https://docs.google.com/spreadsheets/d/1MYpwnb9L0EC0XnsaLSEuaaJrsjGydcQbpuF1-3vlDSA',
    'response_sheet_id': '1MYpwnb9L0EC0XnsaLSEuaaJrsjGydcQbpuF1-3vlDSA',

    # Sheet name for responses (default: "Form Responses 1")
    'response_sheet_name': 'Form Responses 1',
}

# ============================================================
# ENTRY ID MAPPINGS
# ============================================================

# Section 1: Client Information
ENTRY_IDS_CLIENT = {
    'client_type': 'entry.273260877',
    'company_name': 'entry.1110217337',
    'contact_name': 'entry.1047102560',
    'contact_email': 'entry.2028889124',
    'contact_phone': 'entry.1681376801',
}

# Section 2: Order Details (10 product lines)
# Each line has: product_name, quantity, customization_notes
ENTRY_IDS_PRODUCTS = {
    'line_1_name': 'entry.1337105603',
    'line_1_qty': 'entry.586023070',
    'line_1_notes': 'entry.1349546825',

    'line_2_name': 'entry.1611928512',
    'line_2_qty': 'entry.1640551779',
    'line_2_notes': 'entry.1982565920',

    'line_3_name': 'entry.1723305456',
    'line_3_qty': 'entry.74889863',
    'line_3_notes': 'entry.88102384',

    'line_4_name': 'entry.1145436912',
    'line_4_qty': 'entry.1128253267',
    'line_4_notes': 'entry.540946101',

    'line_5_name': 'entry.1049998909',
    'line_5_qty': 'entry.1145723726',
    'line_5_notes': 'entry.1315006826',

    'line_6_name': 'entry.1243609406',
    'line_6_qty': 'entry.851640586',
    'line_6_notes': 'entry.620182536',

    'line_7_name': 'entry.585648481',
    'line_7_qty': 'entry.1650491805',
    'line_7_notes': 'entry.576018945',

    'line_8_name': 'entry.498022722',
    'line_8_qty': 'entry.1189819868',
    'line_8_notes': 'entry.2129410972',

    'line_9_name': 'entry.1363583718',
    'line_9_qty': 'entry.1317826893',
    'line_9_notes': 'entry.1698707742',

    'line_10_name': 'entry.1736567090',
    'line_10_qty': 'entry.1829499248',
    'line_10_notes': 'entry.1629422282',
}

# Section 3: Shipping & Delivery
ENTRY_IDS_SHIPPING = {
    'shipping_address': 'entry.482533612',
    'billing_address': 'entry.101032256',
    'drop_shipping': 'entry.589673738',
    'drop_shipping_instructions': 'entry.1033317514',
    'in_hands_date': 'entry.1347572423',  # Format: YYYY-MM-DD
}

# Section 4: Impact Cards & Payment
ENTRY_IDS_PAYMENT = {
    'impact_cards': 'entry.543181620',
    'impact_card_selection': 'entry.886486601',  # Checkbox - multiple values possible
    'payment_preference': 'entry.1118933684',
    'payment_method': 'entry.1659079798',
}

# Section 5: Additional Notes
ENTRY_IDS_NOTES = {
    'special_requests': 'entry.1220778878',
}

# Combined entry IDs for easy access
ALL_ENTRY_IDS = {
    **ENTRY_IDS_CLIENT,
    **ENTRY_IDS_PRODUCTS,
    **ENTRY_IDS_SHIPPING,
    **ENTRY_IDS_PAYMENT,
    **ENTRY_IDS_NOTES,
}

# ============================================================
# RESPONSE SHEET COLUMN MAPPINGS
# ============================================================

# Column names in response sheet (as they appear in Google Forms responses)
RESPONSE_COLUMNS = {
    # Auto-generated by Google Forms
    'timestamp': 'Timestamp',
    'email': 'Email Address',

    # Section 1: Client Information (note: * indicates required fields in form)
    'client_type': 'Client Type *',
    'company_name': 'Company Name *',
    'contact_name': 'Contact Name *',
    'contact_email': 'Contact Email *',
    'contact_phone': 'Contact Phone',

    # Section 2: Products (10 lines × 3 fields = 30 columns)
    'line_1_name': 'Product Line 1 - Product Name',
    'line_1_qty': 'Product Line 1 - Quantity',
    'line_1_notes': 'Product Line 1 - Customization Notes',

    'line_2_name': 'Product Line 2 - Product Name',
    'line_2_qty': 'Product Line 2 - Quantity',
    'line_2_notes': 'Product Line 2 - Customization Notes',

    'line_3_name': 'Product Line 3 - Product Name',
    'line_3_qty': 'Product Line 3 - Quantity',
    'line_3_notes': 'Product Line 3 - Customization Notes',

    'line_4_name': 'Product Line 4 - Product Name',
    'line_4_qty': 'Product Line 4 - Quantity',
    'line_4_notes': 'Product Line 4 - Customization Notes',

    'line_5_name': 'Product Line 5 - Product Name',
    'line_5_qty': 'Product Line 5 - Quantity',
    'line_5_notes': 'Product Line 5 - Customization Notes',

    'line_6_name': 'Product Line 6 - Product Name',
    'line_6_qty': 'Product Line 6 - Quantity',
    'line_6_notes': 'Product Line 6 - Customization Notes',

    'line_7_name': 'Product Line 7 - Product Name',
    'line_7_qty': 'Product Line 7 - Quantity',
    'line_7_notes': 'Product Line 7 - Customization Notes',

    'line_8_name': 'Product Line 8 - Product Name',
    'line_8_qty': 'Product Line 8 - Quantity',
    'line_8_notes': 'Product Line 8 - Customization Notes',

    'line_9_name': 'Product Line 9 - Product Name',
    'line_9_qty': 'Product Line 9 - Quantity',
    'line_9_notes': 'Product Line 9 - Customization Notes',

    'line_10_name': 'Product Line 10 - Product Name',
    'line_10_qty': 'Product Line 10 - Quantity',
    'line_10_notes': 'Product Line 10 - Customization Notes',

    # Section 3: Shipping & Delivery
    'shipping_address': 'Shipping Address *',
    'billing_address': 'Billing Address (if different from shipping)',
    'drop_shipping': 'Will this order be drop-shipped? *',
    'drop_shipping_instructions': 'Drop-Shipping Instructions',
    'in_hands_date': 'In-Hands Date (When do you need this order?) *',

    # Section 4: Impact Cards & Payment
    'impact_cards': 'Would you like Impact Cards included?',
    'impact_card_selection': 'Impact Card Selection',
    'payment_preference': 'Payment Preference *',
    'payment_method': 'Payment Method *',

    # Section 5: Additional Notes
    'special_requests': 'Special Requests, Notes, or Questions',

    # Tracking columns (added manually to response sheet starting at column AR)
    'imported': 'Imported?',
    'order_id': 'Order ID',
    'imported_by': 'Imported By',
    'import_date': 'Import Date',
}

# ============================================================
# FIELD VALIDATION RULES
# ============================================================

# Maximum number of product lines supported
MAX_PRODUCT_LINES = 10

# Date format for In-Hands Date field
DATE_FORMAT = 'YYYY-MM-DD'

# Special field types
CHECKBOX_FIELDS = [
    'impact_card_selection',  # Can have multiple values
]

# Required fields (client must fill these)
REQUIRED_FIELDS_CLIENT_SIDE = [
    'client_type',
    'company_name',
    'contact_name',
    'contact_email',
    'shipping_address',
    'drop_shipping',
    'in_hands_date',
    'payment_preference',
    'payment_method',
]

# Fields that are pre-filled by exec (in Tab 2)
PREFILLED_FIELDS = [
    'client_type',
    'company_name',
    'contact_name',
    'contact_email',
    'contact_phone',
    # All product lines (name + qty, notes optional)
]

# Fields that client completes
CLIENT_COMPLETES_FIELDS = [
    'shipping_address',
    'billing_address',
    'drop_shipping',
    'drop_shipping_instructions',
    'in_hands_date',
    'impact_cards',
    'impact_card_selection',
    'payment_preference',
    'payment_method',
    'special_requests',
]
